curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 143339, 111544, '6 – 2')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 111536, 132752, '6 – 0')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 2504096, 143957, '6 – 5')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 134919, 126326, '6 – 0')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 102879, 134416, '6 – 4')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 141802, 144763, '6 – 5')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 136120, 121560, '7 – 1')")
curseur.execute(f"INSERT INTO match_individuel VALUES ((SELECT COUNT(*) FROM match_individuel), {idev}, {id_manche}, 111530, 126572, '7 – 3')")
